name: opencood
channels:
  - defaults
dependencies:
  - pip==21.1.2
  - python==3.9.11
  - pip:
    - matplotlib==3.4.2
    - numpy
    - open3d
    - opencv-python
    - cython
    - pygame
    - tensorboardX
    - shapely==2.0.0
    - einops
    - cumm
    - timm
